# Generated by Django 4.2.6 on 2023-12-11 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=50)),
                ('album_release_date', models.DateTimeField()),
                ('album_rating', models.IntegerField()),
                ('musician', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='musician.musicians')),
            ],
        ),
    ]
