# Generated by Django 4.2.6 on 2023-12-11 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album_form',
            name='album_release_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
